### ISSUE TITLE
Do not require bags to be std::set<…>

### ISSUE THREAD

**Issue by spth** [freetdi/tdlib#28] opened 2018-09-26 12:11 UTC
Currently, treedec requires the bags to be of type std::set<…>. However, for the common case of small tree-width, std:.set is not an optimal choice (expensive allocation, not cache-friendly).

For an experimental lospre version in SDCC, it seems to me that the std::set<…> is indeed a performance problem. So I wanted to try to use a boost::container::flat_set<…> instead. It has the same interface as std::set<…>. However, the use of std::set<…> is currently hardcoded in treedec.

treedec should work with any container that offers the necessary operations, so users can freely choose std::set<…>, boost::container:.flat_set<…> or another suitable container.

Philipp

P.S.: However, for boost::container::flat_set<…>, erasing elements invalidates iterators. I do not know if this would be a problem fro treedec.

**Comment by felix-salfelder** [comment] 2018-09-26 12:27
On Wed, Sep 26, 2018 at 05:11:26AM -0700, Philipp Klaus Krause wrote:
> Currently, treedec requires the bags to be of type std::set<…>.
> However, for the common case of small tree-width, std:.set is not an
> optimal choice (expensive allocation, not cache-friendly).

most of treedec has been rewritten to leave the choice to the user. some
of the old code still hardwires sets though. nobody is currently working
on this, so we need to priotise. please be more specific about what you
actually need.

> For an experimental lospre version in SDCC, it seems to me that the
> std::set<…> is indeed a performance problem.

it is just about always a performance problem

> However, the use of std::set<…> is currently hardcoded in treedec.

in what part? have a look at tests/dead_simple.cc

    typedef boost::adjacency_list<boost::vecS, boost::vecS, boost::undirectedS> G;
    [..]
    typedef treedec::thorup<G> thorupAlgorithm;

G is made from vectors, and hence thorupAlgorithm should operate on these vectors. if
it doesn't, that is a bug. certainly, other algorithms do it that way.

> treedec should work with any container that offers the necessary operations,
so users can freely choose std::set<…>, boost::container:.flat_set<…> or
another suitable container.

yes. (newer) treedec code was meant to operate on the graphs the way you
provide them, as long as they have a boost::graph interface. it should choose a
sensible strategy, but it can as well be configured using the second argument
to the algorithm.

hth

**Comment by spth** [comment] 2018-09-26 12:59
I'm not sure I understand the dead_simple example - after all it is written in C++, which to me is not really a readable language - but I think it uses std::set:

It uses treedec::graph_traits<G>::treedec_type for the tree-decomposition.
It looks to me as if according to graph_traits.hpp, treedec_type is treedec_chooser<G_t>::type.
And in treedec_chooser, I find typedef std::set<unsigned> bag_type;

Philipp

**Comment by spth** [comment] 2018-09-26 13:14
I'll see how far I can get in making it work (and probably come back soon as I run into problems).

Philipp

**Comment by felix-salfelder** [comment] 2018-09-26 13:28
On Wed, Sep 26, 2018 at 12:59:33PM +0000, Philipp Klaus Krause wrote:
> I'm not sure I understand the dead_simple example - after all it is
> written in C++, which to me is not really a readable language - but I
> think it uses std::set:
> 
> It uses treedec::graph_traits<G>::treedec_type for the tree-decomposition.
> It looks to me as if according to graph_traits.hpp, treedec_type is treedec_chooser<G_t>::type.
> And in treedec_chooser, I find typedef std::set<unsigned> bag_type;

the mechanism behind this is as follows.

    template<class G>
    treedec_chooser{
    	std::set<unsigned> bag_type;
    };

determines some_bag_type that is then declared in

typedef treedec_chooser<SOME_GRAPH>::bag_type some_bag_type; // a set.

if you have your own graph, and you put in an override like

    template<>
    treedec_chooser<MY_GRAPH>{
    	std::vector<unsigned> bag_type;
    };

then you get

typedef treedec_chooser<MY_GRAPH>::bag_type my_bag_type; // a vector!

that override is valid, and effective, even if my_bag_type is deeply
nested in some other code. we have overrides like this in place for
several standard graph classes, but certainly not for all of them.

that said, in principle, it could work. but right now i am not sure
whether thorup actually respects the override, nor do i know whether
your graph already has an override in place.

please, send me a minimal working example. i will double check and add
it to the tests.

thanks

**Comment by spth** [comment] 2018-09-26 14:09
It seems tome as if the error in my modified SDCC happens at treedec::get_width(). But whenever I try to create a small example for treedec::get_width() (either from scratch or by adding a get_width(vt) to tests/custom_td.cpp) I just get lots of "error: forming reference to void" instead of the error I see in the modified SDCC.

Philipp

**Comment by felix-salfelder** [comment] 2018-09-26 15:05
On Wed, Sep 26, 2018 at 07:09:32AM -0700, Philipp Klaus Krause wrote:
> It seems tome as if the error in my modified SDCC happens at
> treedec::get_width(). But whenever I try to create a small example for
> treedec::get_width() (either from scratch or by adding a get_width(vt)
> to tests/custom_td.cpp) I just get lots of "error: forming reference
> to void" instead of the error I see in the modified SDCC.

found a bug. in fact, there was a leftover hardwired set<u>.

get_width(vt) is now working in develop, and tested in custom_td.cpp.

thanks!

**Comment by spth** [comment] 2018-09-26 16:37
Thanks for the quick fix. It seems there is a similar issue when trying to use treedec::comb::PP_FI_TM with a bag type other than std::set<…>:

~~~~
…
/usr/local/include/treedec/combinations.hpp:278:26:   required from ‘void treedec::comb::PP_FI_TM<G, CFGT>::get_tree_decomposition(TT&) const [with TT = boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, tree_dec_lospre_node>; G = boost::adjacency_list<boost::setS, boost::vecS, boost::undirectedS>; CFGT = treedec::algo::default_config]’
SDCCtree_dec.hpp:647:3:   required from ‘void get_nice_tree_decomposition(T_t&, const G_t&) [with T_t = boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, tree_dec_lospre_node>; G_t = boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, bbcfg_lospre_node, float>]’
SDCClospre.cc:1042:70:   required from here
/usr/include/boost/property_map/property_map.hpp:309:44: error: no match for ‘operator=’ (operand types are ‘boost::bagstuff::treebagpmap<boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, tree_dec_lospre_node> >::B’ {aka ‘boost::container::flat_set<unsigned int>’} and ‘const std::set<unsigned int>’)
…
~~~~

**Comment by felix-salfelder** [comment] 2018-09-26 17:58
On Wed, Sep 26, 2018 at 04:37:38PM +0000, Philipp Klaus Krause wrote:
> Thanks for the quick fix. It seems there is a similar issue when
> trying to use treedec::comb::PP_FI_TM with a bag type other than
> std::set<…>:

reproduced, thanks.

i'm afraid this one is not a bug. it's just not complete.

some old combination code gets routed through a kludge in PP.

    // legacy support. don't use. don't touch.
    template<class GG>
    void get_graph(GG& gg) {
    	assert(boost::is_directed(_g));
    	GG gr;
    	[...]
    }

a better/direct PP interface is used in other places... i am not sure
what the status is.

**Comment by spth** [comment] 2018-09-27 06:28
How about ex17?

~~~~
/usr/include/boost/graph/copy.hpp:349:7:   required from ‘void boost::copy_graph(const VertexListGraph&, MutableGraph&) [with VertexListGraph = boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, treedec::bag_t>; MutableGraph = boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, tree_dec_lospre_node>]’
/usr/local/include/treedec/exact_base.hpp:104:26:   required from ‘void treedec::draft::exact_decomposition<G_t, config, kernel>::get_tree_decomposition(T&) const [with T = boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, tree_dec_lospre_node>; G_t = boost::adjacency_list<boost::setS, boost::vecS, boost::undirectedS>; config = treedec::algo::default_config; kernel = treedec::exact_ta]’
SDCCtree_dec.hpp:647:3:   required from ‘void get_nice_tree_decomposition(T_t&, const G_t&) [with T_t = boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, tree_dec_lospre_node>; G_t = boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, bbcfg_lospre_node, float>]’
SDCClospre.cc:1042:70:   required from here
/usr/include/boost/property_map/property_map.hpp:309:44: error: no match for ‘operator=’ (operand types are ‘boost::bagstuff::treebagpmap<boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, tree_dec_lospre_node> >::B’ {aka ‘boost::container::flat_set<unsigned int>’} and ‘const std::set<unsigned int>’)
~~~~

Philipp

P.S.: Thorup compiles with the boost::container::flat_set<…>

**Comment by felix-salfelder** [comment] 2018-10-04 18:09
fixed in develop

**Closed by felix-salfelder** 2018-10-04 18:09 UTC
